---
- hosts: all
  become: yes
  tasks:
   - name: "Install PostgreSQL"
     yum: name=https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
   - name: "install postgresql server"
     yum: name={{ item }} state=installed
     with_items:
        - postgresql
        - postgresql-server

