---
- hosts: all
  become: yes
  tasks:
    - name: "Install Nginx"
      package:
        name: nginx
        state: present

    - name: "Put file"
      template:
         src: index.html.j2 
         dest: /usr/share/nginx/html/index.html

    - name: "Enable Nginx"
      service:
         name: nginx
         state: restarted
         enabled: yes 

